### ISSUE TITLE
[BUG] Buildings not collecting, energy not filling up since server change

### ISSUE THREAD

**Issue by techfirstuk** [matronator/GlobalCollapse#28] opened 2023-09-22 18:41 UTC
Since the server change the energy isnt re-filling and the buildings are not paying out.

**Comment by matronator** [comment] 2023-09-23 19:13
I can't reproduce the energy not re-filling. When I go resting, it fills up normally. The buildings were caused by badly set-up CRON, it should be fixed now.

**Closed by matronator** 2023-09-23 19:13 UTC
Labels: type: bug, stage: investigating
